### ISSUE TITLE
yarl version

### ISSUE THREAD

**Issue by nabobalis** [conda-forge/aiohttp-feedstock#43]
Recently we noticed our conda forge test suite failing on:
```
pkg_resources.ContextualVersionConflict: (yarl 1.6.2 (/home/vsts/work/1/s/.tox/py38-conda/lib/python3.8/site-packages), Requirement.parse('yarl<1.6.0,>=1.0'), {'aiohttp'})
```
As far as I was aware the aiohttp setup.py pins to <2.0, is there any chance this restriction could be changed in the recipe?

**Comment by ocefpaf** [comment]
Latest released version is https://github.com/aio-libs/aiohttp/blob/19405036da709906b3349298569c4ae8696d436b/setup.py#L79

**Comment by nabobalis** [comment]
My fault for checking the wrong version. But now we have a conflict where we don't see one using pip.

I guess excluding the rebuild package and using an older version is my only option?

**Comment by ocefpaf** [comment]
> My fault for checking the wrong version. But now we have a conflict where we don't see one using pip.

Pip does not have a solver (yet).

> I guess excluding the rebuild package and using an older version is my only option?

Probably. I also need to remove a bad pinned version from our channel. Working on it.
