### ISSUE TITLE
Build with arm64 support

### ISSUE THREAD

**Issue by holdenk** [conda-forge/aiohttp-feedstock#47]
It would be nice to use this with arm64, pip installing it works. I tried adding this to the needs-migration thing, but it doesn't seem like the bot did it's magic.

**Comment by ocefpaf** [comment]
We may be missing a dependency. You [can try this and re-render](https://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=aarch64#linux-aarch64) to test it.
